# Generated by Django 4.1.3 on 2022-11-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=45)),
                ('number_of_copies', models.IntegerField()),
                ('year_of_publication', models.DateField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bookstore.author')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('book_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bookstore.book')),
                ('client_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bookstore.client')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bookstore.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='section_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bookstore.section'),
        ),
    ]
