# Generated by Django 4.1.5 on 2023-01-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0004_alter_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book_book',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
