# Generated by Django 4.1.5 on 2023-01-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0005_remove_order_book_book_remove_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bookstore.book'),
        ),
    ]
