# Generated by Django 4.1.5 on 2023-01-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0006_order_book_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='book_info',
            new_name='book_title',
        ),
    ]
