# Generated by Django 4.1.5 on 2023-01-15 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0007_rename_book_info_order_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bookstore.Order.book_price+', to='Bookstore.book'),
        ),
        migrations.AlterField(
            model_name='order',
            name='book_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bookstore.Order.book_title+', to='Bookstore.book'),
        ),
    ]
