# Generated by Django 4.1.5 on 2023-01-15 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0008_order_book_price_alter_order_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='book_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bookstore.book'),
        ),
    ]
