# Generated by Django 4.1.5 on 2023-01-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0009_remove_order_book_price_alter_order_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book_title',
        ),
        migrations.AddField(
            model_name='order',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_title', to='Bookstore.book'),
        ),
    ]
