# Generated by Django 4.1.5 on 2023-01-15 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0011_rename_book_order_book_title_order_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='book_title',
        ),
        migrations.AddField(
            model_name='order',
            name='book_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bookstore.book'),
        ),
    ]
