# Generated by Django 4.1.5 on 2023-01-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0012_remove_order_book_price_remove_order_book_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='book_info',
            new_name='book',
        ),
    ]
