# Generated by Django 4.1.5 on 2023-01-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0014_rename_book_order_book_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_client',
        ),
    ]
