# Generated by Django 4.1.5 on 2023-01-07 17:45

import Bookstore.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, validators=[Bookstore.models.Name_validation])),
                ('last_name', models.CharField(max_length=45, validators=[Bookstore.models.Name_validation])),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50, validators=[Bookstore.models.Name_validation])),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[Bookstore.models.Price_validation])),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=45)),
                ('number_of_copies', models.IntegerField()),
                ('year_of_publication', models.DateField(validators=[Bookstore.models.Date_validation])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bookstore.author', validators=[Bookstore.models.Name_validation])),
                ('genre_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bookstore.genre', validators=[Bookstore.models.Name_validation])),
            ],
        ),
    ]
