# Generated by Django 4.1.5 on 2023-01-14 14:49

import Bookstore.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, validators=[Bookstore.models.Name_validation])),
                ('last_name', models.CharField(max_length=45, validators=[Bookstore.models.Name_validation])),
                ('birthdate', models.DateField(validators=[Bookstore.models.Date_validation])),
                ('city', models.CharField(max_length=45, validators=[Bookstore.models.Name_validation])),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(validators=[Bookstore.models.Date_validation])),
                ('price', models.FloatField(null=True, validators=[Bookstore.models.Price_validation])),
                ('book_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bookstore.book')),
                ('client_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bookstore.client')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
