# Generated by Django 4.1.5 on 2023-01-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0002_client_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
    ]
